services:
  db:
    image: postgres
    volumes:
      - data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
  bot:
    build:
      context: .
    volumes:
      - ./:/app
    command: ["poetry", "run", "python", "main.py"]

volumes:
  data:
